[package]
name = "jitkit27-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "jitkit27_ffi"
crate-type = ["staticlib"]

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
idevice = { git = "https://github.com/jkcoxson/idevice.git", rev = "7bd551c16c6dd2e058740d85a2d9399a51a776e9", features = ["remote_pairing", "tunnel_tcp_stack", "rsd", "tcp", "xpc", "pair", "aws-lc"] }
